IF EXISTS(SELECT 1 FROM [INFORMATION_SCHEMA].[TABLES]
	WHERE TABLE_NAME = 'STG_CUSTOMERS')
BEGIN
	DROP TABLE [dbo].[STG_CUSTOMERS]
END

CREATE TABLE [dbo].[STG_CUSTOMERS] (
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	in_file VARCHAR(50)
);